using System;

/*
    Theory:
    Partial Class in C# is a feature that allows the definition of a class to be split into multiple files.
    Each part of the class is declared with the "partial"  keyword. When compiled, all the parts are combined into a single clas definition.



    //instruction how to run the program
    there are twofiles named PartialClass1.cs and PartialClass2.cs the final class is generated by combining two classes.
*/


// copy below code in program.cs
// class Program
// {
//     static void Main(string[] args){
//         PartialClass obj = new PartialClass();

//         //calling methods from both partial class
//         obj.Method1();
//         obj.Method2();
//     }
// }

